<!--index-->
<div class="index">
    <h2>タイムラインを"ふわふわ"表示したいSNSを選んでください</h2>
    <h3>対応：Tumblr　準備中：Facebook,Twitter,Instagram</h3>
    <p class="version-text">Version 1.0.0</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-facebook">Facebbok</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-twitter">Twitter</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-tumblr">Tumblr</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-instagram">Instagram</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="/timeline/display" method="post" class="form-area form-facebook">
                <input type="submit">Get Timeline
                <p>facebook</p>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/display" method="post" class="form-area form-twitter">
                <input type="submit">Get Timeline
                <p>twitter</p>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/display" method="post" class="form-area form-tumblr">
                <input type="submit">Get Timeline
                <p>tumblr</p>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/display" method="post" class="form-area form-instagram">
                <input type="submit">Get Timeline
                <p>instagram</p>
            </form>
        </div>
    </div>
</div>
<script>
    $(function(){
        $('.btn-facebook').on('click', function() {
            $(".form-twitter").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").hide(100);
            $(".form-facebook").toggle(500);
        });
        $('.btn-twitter').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").hide(100);
            $(".form-twitter").toggle(500);
        });
        $('.btn-tumblr').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-twitter").hide(100);
            $(".form-instagram").hide(100);
            $(".form-tumblr").toggle(500);
        });
        $('.btn-instagram').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-twitter").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").toggle(500);
        });
    });
</script>