<!--index-->
<div class="index">
    <h2>タイムラインを"ふわふわ"表示したいSNSを選んでください</h2>
    <h3>対応：Tumblr　準備中：Facebook,Twitter,Instagram</h3>
    <p class="version-text">Version 1.0.0</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-facebook">Facebbok</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-twitter">Twitter</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-tumblr">Tumblr</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-instagram">Instagram</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="/timeline/facebook" method="post" class="form-area form-facebook">
                <input type="submit">Get Timeline
                <p>facebook</p>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/twitter" method="post" class="form-area form-twitter">
                <input type="submit">Get Timeline
                <p>twitter</p>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/tumblr" method="get" class="form-area form-tumblr">
                <ul>
                    <li>
                        <label class="radio-label">
                            <input type="radio" name="radio" class="radio" id="tumblr-self" value="self"/>自分のタイムライン
                        </label>
                        <div class="conditions-area tumblr-self">
                            <label>
                                <input type="checkbox" id="type" name="type" value="photo">画像のみ表示
                            </label>
                        </div>
                    </li>
                    <li>
                        <label class="radio-label">
                            <input type="radio" name="radio" class="radio" id="tumblr-other" value="other"/>特定のブログ
                        </label>
                        <div class="conditions-area tumblr-other">
                            <input type="text" class="form-control" id="url-text" name="url" placeholder="ブログのURL">
                        </div>
                    </li>
                    <li>
                        <label class="radio-label">
                            <input type="radio" name="radio" class="radio" id="tumblr-tag" value="tag"/>タグ検索
                        </label>
                        <div class="conditions-area tumblr-tag">
                            <input type="text" class="form-control" id="tag-text" name="tag" placeholder="タグ">
                        </div>
                    </li>
                    <li>
                        <label class="speed-label">切り替えスピード（秒）
                            <input type="text" name="speed" maxlength="3" class="form-control form-speed">
                            <small>※未設定の場合は3秒になります</small>
                        </label>
                    </li>
                    <li>
                        <button class="btn btn-primary btn-submit" type="submit">タイムライン表示</button>
                    </li>
                </ul>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/instagram" method="post" class="form-area form-instagram">
                <input type="submit">Get Timeline
                <p>instagram</p>
            </form>
        </div>
    </div>
</div>
<script>
    $(function(){
        $('.btn-facebook').on('click', function() {
            $(".form-twitter").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").hide(100);
            $(".form-facebook").toggle(500);
        });
        $('.btn-twitter').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").hide(100);
            $(".form-twitter").toggle(500);
        });
        $('.btn-tumblr').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-twitter").hide(100);
            $(".form-instagram").hide(100);
            $(".form-tumblr").toggle(500);
        });
        $('.btn-instagram').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-twitter").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").toggle(500);
        });
        $('#tumblr-self').on('change', function() {
            $(".tumblr-tag").hide(200);
            $(".tumblr-other").hide(200);
            $(".tumblr-self").toggle(200);
        });
        $('#tumblr-other').on('change', function() {
            $(".tumblr-self").hide(200);
            $(".tumblr-tag").hide(200);
            $(".tumblr-other").toggle(200);
        });
        $('#tumblr-tag').on('change', function() {
            $(".tumblr-self").hide(200);
            $(".tumblr-other").hide(200);
            $(".tumblr-tag").toggle(200);
        });
    });
</script>