<!--index-->
<div class="index">
    <h1>
        <img class="head-logo" src="./img/toplogo.png">
    </h1>
    <h2>SNSのタイムラインをスクロールすることすらめんどくさいあなたへ…<br>
        あなたのタイムラインが"ふわふわ"表示されます。
        それをただぼーっと見つめててください。<br>
        食事中や作業中などにタイムラインをチェックしたい人にオススメです
    </h2>
    <div class="sns">
        <ul>
            <li>
                <div class="fb-like" data-href="http://fluffy-timeline.com/" data-layout="button" data-action="like" data-size="large" data-show-faces="false" data-share="true"></div>
                <div id="fb-root"></div><script>(function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.9";fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));</script>
            </li>
            <li>
                <a href="https://twitter.com/share" class="twitter-share-button" data-size="large">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
            </li>
        </ul>
    </div>
    <p>&copy; <?php echo date('Y') ?> by Fluffy Timeline <?php echo $this->translate('All rights reserved.') ?></p>
    <p class="version-text">Version 1.0.0</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-facebook">Facebbok</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-twitter">Twitter</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-tumblr">Tumblr</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-block btn-instagram">Instagram</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="/timeline/facebook" method="post" class="form-area form-facebook">
                <p>準備中</p>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/tumblr" method="get" class="form-area form-twitter">
                <p>準備中</p>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/tumblr" method="get" class="form-area form-tumblr">
                <ul>
                    <li>
                        <input type="radio" name="radio" class="radio" id="tumblr-self" value="self"/>
                        <label for="tumblr-self" class="radio-label">自分のダッシュボード</label>
                        <div class="conditions-area tumblr-self">
                            <label>
                                <input type="checkbox" id="type" name="type" value="photo">画像のみ表示
                            </label>
                        </div>
                    </li>
                    <li>
                        <input type="radio" name="radio" class="radio" id="tumblr-other" value="other"/>
                        <label for="tumblr-other" class="radio-label">特定のブログ</label>
                        <div class="conditions-area tumblr-other">
                            <input type="text" class="form-control" id="url-text" name="url" placeholder="ブログのURL">
                        </div>
                    </li>
                    <li>
                        <input type="radio" name="radio" class="radio" id="tumblr-tag" value="tag"/>
                        <label for="tumblr-tag" class="radio-label">タグ検索</label>
                        <div class="conditions-area tumblr-tag">
                            <input type="text" class="form-control" id="tag-text" name="tag" placeholder="タグ">
                        </div>
                    </li>
                    <li>
                        <label class="speed-label">切り替えスピード（秒）
                            <input type="text" name="speed" maxlength="3" class="form-control form-speed">
                            <small>※未設定の場合は3秒になります</small>
                        </label>
                    </li>
                    <li>
                        <button class="btn btn-primary btn-submit" type="submit">タイムライン表示</button>
                    </li>
                </ul>
            </form>
        </div>
        <div class="col-md-12">
            <form action="/timeline/instagram" method="post" class="form-area form-instagram">
                <p>準備中</p>
            </form>
        </div>
    </div>
</div>
<script>
    $(function(){
        $('.btn-facebook').on('click', function() {
            $(".form-twitter").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").hide(100);
            $(".form-facebook").toggle(500);
        });
        $('.btn-twitter').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").hide(100);
            $(".form-twitter").toggle(500);
        });
        $('.btn-tumblr').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-twitter").hide(100);
            $(".form-instagram").hide(100);
            $(".form-tumblr").toggle(500);
        });
        $('.btn-instagram').on('click', function() {
            $(".form-facebook").hide(100);
            $(".form-twitter").hide(100);
            $(".form-tumblr").hide(100);
            $(".form-instagram").toggle(500);
        });
        $('#tumblr-self').on('click', function() {
            $(".tumblr-tag").hide(200);
            $(".tumblr-other").hide(200);
            $(".tumblr-self").toggle(200);
        });
        $('#tumblr-other').on('click', function() {
            $(".tumblr-self").hide(200);
            $(".tumblr-tag").hide(200);
            $(".tumblr-other").toggle(200);
        });
        $('#tumblr-tag').on('click', function() {
            $(".tumblr-self").hide(200);
            $(".tumblr-other").hide(200);
            $(".tumblr-tag").toggle(200);
        });
    });
</script>