<!--index-->
<div class="container-fluid">
    <ul id="timeline-area">
        <li class="hoge">
            <img src="/img/cat1.jpg" alt="1枚目の画像"/>
        </li>
        <li class="hoge">
            <img src="/img/cat2.jpg" alt="1枚目の画像"/>
        </li>
        <li class="hoge">
            <img src="/img/cat3.jpg" alt="1枚目の画像"/>
        </li>
        <li class="hoge">
            <img src="/img/cat4.jpg" alt="1枚目の画像"/>
        </li>
    </ul>
</div>

<script type="text/javascript">
    $(function(){
        $("#timeline-area").find("li").hide();
        $("#timeline-area").find("li:first").stop().fadeIn(1000);

        setInterval(function(){
            $("#timeline-area").find("li:first-child").fadeOut(1000)
                .next("li").fadeIn(1000)
                .end().appendTo("#timeline-area");
        }, 3000);
    });
</script>
