<?php echo $this->doctype(); ?>

<html lang="en">
    <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
        <meta name="google-site-verification" content="LEvTVAPnau4r6oJnooFCr-Hu9qv2vGX2TJnd0-nZQ_E" />
        <meta charset="utf-8">
        <?php echo $this->headTitle('ふわふわタイムライン|Fluffy Timeline')?>
        <meta name="description" content="SNSのタイムラインをスクロールすることすらめんどくさいあなたへ…あなたのタイムラインが自動でふわふわとフェードイン/アウトして表示されます。" />

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/site.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.10.1.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <!-- OGP -->
        <meta property="og:title" content="ふわふわタイムライン|Fluffy Timeline" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://fluffy-timeline.com/" />
        <meta property="og:image" content="/img/toplogo.png" />
        <meta property="og:site_name"  content="http://fluffy-timeline.com/" />
        <meta property="og:description" content="SNSのタイムラインをスクロールすることすらめんどくさいあなたへ…あなたのタイムラインがふわふわ表示されます。" />
        <!-- <meta property="fb:app_id" content="App ID" />
        <meta property="article:publisher" content="FacebookページのURL" /> -->
        <meta name="twitter:card" content="summary" />
        <!-- <meta name="twitter:site" content="@Twitter" />
        <meta name="twitter:image" content="サムネイル画像のURL" /> -->
    </head>
    <body class="home">
    <div class="background"></div>
    <div class="wrap docs-header header--noBackground">
        <div class="contents">
            <nav class="navbar navbar-default navbar-custom" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/"><img src="/img/headerlogo.png" height="40"></a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a class="nav-link" href="/timeline/contact">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                <?php echo $this->content; ?>
            </div> <!-- /container -->
        </div><!--
        <footer class="site-footer">
            <p>&copy; 2005 - <?php echo date('Y') ?> by Fluffy Timeline <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>-->
        <?php echo $this->inlineScript() ?>
    </div>
    <script>
        var speed = 1000;
        var times = 3000;
        var bgimages = [
            '../img/back1.png',
            '../img/back2.png',
            '../img/back3.png'
        ];
        $(function(){
            var thisnum = 0;
            setInterval(function(){
                $(".background").fadeOut(speed,function(){
                    thisnum = thisnum === bgimages.length - 1 ? 0 : thisnum + 1;
                    $(this).css({"background-image":"url("+bgimages[thisnum]+")"}).fadeIn(speed);

                });
            }, times);
        });
    </script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-40621186-8', 'auto');
        ga('send', 'pageview');

    </script>
    </body>
</html>
