<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta name="google-site-verification" content="myJMospzZCV5r3e5rkTJKXWNDJ37AA3ZZzHc5j9SNpI" />
        <meta charset="utf-8">
        <?php echo $this->headTitle('ふわふわタイムライン')?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/site.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.10.1.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <!-- OGP -->
        <meta property="og:title" content="ふわふわタイムライン" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="http://fluffy-timeline.com/" />
        <meta property="og:image" content="/img/toplogo.png" />
        <meta property="og:site_name"  content="http://fluffy-timeline.com/" />
        <meta property="og:description" content="SNSのタイムラインをスクロールすることすらめんどくさいあなたへ…あなたのタイムラインがふわふわ表示されます。 それをただぼーっと見つめててください。食事中や作業中などにタイムラインをチェックしたい人にオススメです" />
        <!-- <meta property="fb:app_id" content="App ID" />
        <meta property="article:publisher" content="FacebookページのURL" /> -->
        <meta name="twitter:card" content="summary" />
        <!-- <meta name="twitter:site" content="@Twitter" />
        <meta name="twitter:image" content="サムネイル画像のURL" /> -->
    </head>
    <body class="home">
    <div class="background"></div>
    <div class="wrap docs-header header--noBackground">
        <div class="contents">
            <nav class="navbar navbar-default navbar-custom" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/"><img src="/img/headerlogo.png" height="40"></a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a class="nav-link" href="/timeline/contact">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                <?php echo $this->content; ?>
            </div> <!-- /container -->
        </div><!--
        <footer class="site-footer">
            <p>&copy; 2005 - <?php echo date('Y') ?> by Fluffy Timeline <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>-->
        <?php echo $this->inlineScript() ?>
    </div>
    <script>
        var speed = 1000;
        var times = 3000;
        var bgimages = [
            '../img/back1.png',
            '../img/back2.png',
            '../img/back3.png'
        ];
        $(function(){
            var thisnum = 0;
            setInterval(function(){
                $(".background").fadeOut(speed,function(){
                    thisnum = thisnum === bgimages.length - 1 ? 0 : thisnum + 1;
                    $(this).css({"background-image":"url("+bgimages[thisnum]+")"}).fadeIn(speed);

                });
            }, times);
        });
    </script>
    </body>
</html>
