<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta name="google-site-verification" content="myJMospzZCV5r3e5rkTJKXWNDJ37AA3ZZzHc5j9SNpI" />
        <meta charset="utf-8">
        <?php echo $this->headTitle('Timeline')?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/site.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.10.1.min.js')
            ->prependFile($this->basePath() . '/js/site.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="home">
    <div class="wrap docs-header header--noBackground">
        <div class="contents">
            <nav class="navbar navbar-default navbar-custom" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index.html"><img src="/img/logo.png" height="40"></a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a class="nav-link" href="getting-started.html">Getting Started</a></li>
                            <li><a class="nav-link" href="documentation.html">Documentation</a></li>
                            <li><a class="nav-link" href="free-psd.html">Free PSD</a></li>
                            <li><a class="nav-link" href="color-picker.html">Color Picker</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                <?php echo $this->content; ?>
            </div> <!-- /container -->
        </div>
        <footer class="site-footer">
            <p>&copy; 2005 - <?php echo date('Y') ?> by Fluffy Timeline <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
        <?php echo $this->inlineScript() ?>
    </div>
    </body>
</html>
